### ISSUE TITLE
Getting error when converting parquet files after updating PyCharm and plugin from 1.1.0 to 1.1.1

### ISSUE THREAD

**Issue by davidpurkiss** [benwatson528/intellij-avro-parquet-plugin#19]
![image](https://user-images.githubusercontent.com/1390673/74330573-cfc6ec00-4d89-11ea-8b20-061201ef37e6.png)

PyCharm 2019.3.3 (Professional Edition)
Build #PY-193.6494.30, built on February 6, 2020

Runtime version: 11.0.5+10-b520.38 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.2
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: 
Non-Bundled Plugins: com.github.redfoos.logstash-intellij-plugin, com.sburlyaev.terminal.plugin, net.ashald.envfile, ru.meanmail.plugin.requirements, uk.co.hadoopathome.intellij.avro.intellijavroviewer

**Comment by benwatson528** [comment]
Hi David,

I switched to the official [`parquet-avro`](https://github.com/apache/parquet-mr/tree/master/parquet-avro) library for 1.1.1, primarily to resolve some major bugs in 1.1.0's JSON parser. This library handles all reading internally and to the latest Parquet specification. As the Parquet development team have [dropped support for INT96](https://issues.apache.org/jira/browse/PARQUET-323), I'm afraid that the plugin will no longer support data containing this field.

It is frustrating that the API fails while converting any records that contain this field rather than simply throwing a warning and continuing, but this is out of my control.

For a workaround you have two options:
- Manually revert to [1.1.0](https://plugins.jetbrains.com/plugin/12281-avro-and-parquet-viewer/update/77314),
 - Update your data to use [INT64's nanosecond support](https://github.com/apache/parquet-format/commit/b879065ac1bee3fe1d770eb3c4b60ab4267044d7).

Regards,

Ben

**Comment by davidpurkiss** [comment]
Thanks for the feedback Ben! I'll revert to the previous version for now.

**Comment by rowandavies** [comment]
INT96 is deprecated in current versions of Parquet, yes.  It is still supported via deprecated methods though, right?

It will take some years before this deprecation flows through to all writing applications.  Meanwhile reading applications may still need to handle this case.  Particularly since many large big data files will include INT96 in Parquet.

It's up to you to decide what use cases you want to support.  But, it would be nice for many of us if we use this tool with the actual files we're likely to be working with over the next few years.  I guess we can stick with v1.1.0 forever, I just wanted to make sure that you knew that would become a common restriction for users.

**Comment by benwatson528** [comment]
Hi Rowan,

Yes it is a shame and I agree with you but it is out of my control. I haven't found another way to read in Parquet files that doesn't directly rely on Spark or a Hadoop Path. Feel free to fork and have a play around if you think you can get it working.

This weekend I will raise an issue and PR with Parquet - I can see it was already fixed for Pig https://github.com/apache/parquet-mr/pull/422. No guarantees how quickly it will be merged in - it looks like there are close to 100 open PRs in that repo at the moment.

Ben

**Comment by benwatson528** [comment]
https://issues.apache.org/jira/browse/PARQUET-1870

**Comment by benwatson528** [comment]
https://github.com/benwatson528/intellij-avro-parquet-plugin/pull/30 - I've published an update to this plugin that will let you view files containing INT96 columns. Look out for an update to 1.1.5 on the IDEA marketplace in the next few days.

**Comment by benwatson528** [comment]
The 1.1.5 update is now live. I've had a response to https://issues.apache.org/jira/browse/PARQUET-1870 and will investigate my options there.
