### ISSUE TITLE
alphabetical order of columns

### ISSUE THREAD

**Issue by kmakiela96** [benwatson528/intellij-avro-parquet-plugin#24]
Hi
Is it possible to change table view in Data so that columns will be in order specified by schema rather than alphabetical order?

**Comment by benwatson528** [comment]
Hi, I'll take a look this weekend. Always happy to have something to do during quarantine!

**Comment by benwatson528** [comment]
This is actually a much harder problem than it might first appear due to the logic around flattening nested JSON records. As JSON is an unordered file format, there's no easy way for me to maintain the order after flattening. The solutions I can think of are likely to be quite fiddly and buggy. I'm going to leave this open in the hope that someone else sees it and can find a neater solution.

**Comment by kmakiela96** [comment]
" As JSON is an unordered file format, there's no easy way for me to maintain the order after flattening. The solutions I can think of are likely to be quite fiddly and buggy" Unfortunately that's what i thought. Nevertheless thx for reply, If i think of something I will post some idea's here. Wish all the best during those tough and bizzare times!
