### ISSUE TITLE
File open as normal file

### ISSUE THREAD

**Issue by m-radzikowski** [benwatson528/intellij-avro-parquet-plugin#41]
Hey,
very useful plugin. I was glad when I found it and realized I do not have to install some separate tool!

Did you think about, instead of adding a tool window, to add support in IntelliJ to open avro and parquet files? I think it should be possible as there are a lot of plugins that add the capability to open different file formats. Also tabs for schema and data like you have right now should be possible, the CSV plugin has something similar (https://plugins.jetbrains.com/plugin/10037-csv-plugin). It would be a little bit more natural.

Just asking if you thought about it and if you plan to develop it in this way.

**Comment by benwatson528** [comment]
Hi Maciej,

Thanks for the kind words. I intentionally made the plugin as a Tool Window because the main Editor pane should be reserved for content that can be edited, and I have no plans for implementing editing functionality (see #40). CSV files don't have the same requirements for schema validation and compilation as Avro and Parquet files, so it would be a fairly challenging problem to solve.

Thanks,

Ben

**Comment by m-radzikowski** [comment]
Ok, I understand. Thanks for explanation.
